# Generated by Django 4.0.10 on 2023-04-11 13:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productline_product'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceProductLine',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('Invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_contract', to='invoices.invoice')),
                ('productLine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_contract', to='products.productline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
