# Generated by Django 4.0.10 on 2023-04-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_type'),
        ('invoices', '0003_remove_invoiceproductline_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_clients', to='clients.client'),
            preserve_default=False,
        ),
    ]
