# Generated by Django 4.0.10 on 2023-04-12 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceproductline',
            old_name='Invoice',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='invoiceproductline',
            old_name='productLine',
            new_name='product_line',
        ),
    ]
