# Generated by Django 4.0.10 on 2023-04-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_rename_invoice_invoiceproductline_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
