# Generated by Django 3.2.18 on 2023-04-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_is_cancelled'),
        ('invoices', '0007_invoice_total_price'),
    ]

    operations = [
    ]
