# Generated by Django 4.0.10 on 2023-05-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoice_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.CharField(default='INV', editable=False, max_length=100),
        ),
    ]
