# Generated by Django 4.0.10 on 2023-05-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_last_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='last_email',
            field=models.CharField(default='unkown', max_length=64),
        ),
    ]
