# Generated by Django 4.0.10 on 2023-05-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_link_mou'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='number',
            field=models.CharField(default='CTR', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='last_email',
            field=models.CharField(default='unknown', max_length=64),
        ),
    ]
