# Generated by Django 4.0.10 on 2023-04-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(db_index=True, default='none', max_length=128),
            preserve_default=False,
        ),
    ]
