# Generated by Django 4.0.10 on 2023-03-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_halokauser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halokauser',
            name='phone',
        ),
    ]
