# Generated by Django 4.0.10 on 2023-03-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_halokauser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='halokauser',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text='e.g 62813xxxxxxx', max_length=16, null=True),
        ),
    ]
