# Generated by Django 4.0.10 on 2023-03-18 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_halokauser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halokauser',
            name='phone',
        ),
    ]
