# Generated by Django 4.0.10 on 2023-04-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_section', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('Invoice', 'Invoice'), ('Agreement', 'Agreement')], max_length=64)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
