# Generated by Django 4.0.10 on 2023-03-12 09:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productbundle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBundleLine',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bundle_lines', to='products.productbundle')),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bundle_lines', to='products.productline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
