# Generated by Django 4.0.10 on 2023-03-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productbundleline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productline',
            name='product',
        ),
    ]
